### ISSUE TITLE
Roleplay Adding Issues

### ISSUE THREAD

**Issue by LVPYassine** [saplayground/San-Andreas-Playground#10]
i got some warnings and errors 

irc included but still i got "Undefined Symbol "IRC_Connect"" ????????

idk the list of errors : 

>  D:\pawno-master\include\SAPData/Freeroam/Server/GMStart.pwn(153) : error 017: undefined symbol "IRC_Connect"
> D:\pawno-master\include\SAPData/Freeroam/Server/GMStart.pwn(155) : error 017: undefined symbol "IRC_SetIntData"
> D:\pawno-master\include\SAPData/Freeroam/Server/GMStart.pwn(157) : error 017: undefined symbol "IRC_Connect"
> D:\pawno-master\include\SAPData/Freeroam/Server/GMStart.pwn(159) : error 017: undefined symbol "IRC_SetIntData"
> D:\pawno-master\include\SAPData/Freeroam/Server/GMStart.pwn(161) : error 017: undefined symbol "IRC_CreateGroup"
> D:\pawno-master\include\SAPData/Freeroam/Chat/ChatManager.json(75) : error 017: undefined symbol "IRC_Say"
> D:\pawno-master\include\SAPData/Roleplay/Player/Death.pwn(16) : warning 203: symbol is never used: "reason"
> D:\pawno-master\include\SAPData/Roleplay/Player/Death.pwn(16) : warning 203: symbol is never used: "killerid"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(209) : warning 203: symbol is never used: "Act"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(209) : warning 203: symbol is never used: "AutomaticRace"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(209) : warning 203: symbol is never used: "BlockPm"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(47) : warning 204: symbol is assigned a value that is never used: "BusPick"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(47 -- 209) : warning 203: symbol is never used: "CNRMenu"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(47 -- 209) : warning 203: symbol is never used: "CNRRefill"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(47 -- 209) : warning 203: symbol is never used: "CPCoords"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(47 -- 209) : warning 203: symbol is never used: "CountAmount"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(47 -- 209) : warning 203: symbol is never used: "CountTimer"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(47 -- 209) : warning 203: symbol is never used: "CreatedRamp"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(47 -- 209) : warning 203: symbol is never used: "FinishCount"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(24) : warning 204: symbol is assigned a value that is never used: "GetinBank"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(25) : warning 204: symbol is assigned a value that is never used: "GetoutBank"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27) : warning 204: symbol is assigned a value that is never used: "GlassEvent"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "InCar"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "Index"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "InitFly"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "IsNumeric"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "IsValidSkin"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(3445) : warning 204: symbol is assigned a value that is never used: "MoneyBagPickup"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(3445 -- 209) : warning 203: symbol is never used: "PlayersCount"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2882) : warning 204: symbol is assigned a value that is never used: "PoliceOP"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881) : warning 204: symbol is assigned a value that is never used: "PoliceP"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "Position"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RaceBusy"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RaceName"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RaceNames"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RacePosition"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RaceStarted"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RaceTick"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RaceTime"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RaceType"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RaceVehCoords"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RaceVehicle"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "Ramp"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2881 -- 209) : warning 203: symbol is never used: "RefillStation"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(3124) : warning 204: symbol is assigned a value that is never used: "RobberOP"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(3122) : warning 204: symbol is assigned a value that is never used: "RobberP"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(3123) : warning 204: symbol is assigned a value that is never used: "RobberP2"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(3123 -- 209) : warning 203: symbol is never used: "Robstart"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(3123 -- 209) : warning 203: symbol is never used: "StartFly"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(3123 -- 209) : warning 203: symbol is never used: "StopFly"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2849) : warning 204: symbol is assigned a value that is never used: "Store1"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2863) : warning 204: symbol is assigned a value that is never used: "Store10"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2864) : warning 204: symbol is assigned a value that is never used: "Store11"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2865) : warning 204: symbol is assigned a value that is never used: "Store11Exit"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2866) : warning 204: symbol is assigned a value that is never used: "Store12"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2867) : warning 204: symbol is assigned a value that is never used: "Store12Exit"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2868) : warning 204: symbol is assigned a value that is never used: "Store13"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2869) : warning 204: symbol is assigned a value that is never used: "Store13Exit"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2870) : warning 204: symbol is assigned a value that is never used: "Store14"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2871) : warning 204: symbol is assigned a value that is never used: "Store15"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2872) : warning 204: symbol is assigned a value that is never used: "Store16"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2873) : warning 204: symbol is assigned a value that is never used: "Store17"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2874) : warning 204: symbol is assigned a value that is never used: "Store17Exit"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2875) : warning 204: symbol is assigned a value that is never used: "Store18"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2876) : warning 204: symbol is assigned a value that is never used: "Store19"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2850) : warning 204: symbol is assigned a value that is never used: "Store2"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2877) : warning 204: symbol is assigned a value that is never used: "Store20"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2878) : warning 204: symbol is assigned a value that is never used: "Store21"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2879) : warning 204: symbol is assigned a value that is never used: "Store22"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2851) : warning 204: symbol is assigned a value that is never used: "Store2Exit"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2852) : warning 204: symbol is assigned a value that is never used: "Store3"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2853) : warning 204: symbol is assigned a value that is never used: "Store3Exit"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2854) : warning 204: symbol is assigned a value that is never used: "Store4"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2855) : warning 204: symbol is assigned a value that is never used: "Store4Exit"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2856) : warning 204: symbol is assigned a value that is never used: "Store5"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2857) : warning 204: symbol is assigned a value that is never used: "Store6"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2858) : warning 204: symbol is assigned a value that is never used: "Store6Exit"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2859) : warning 204: symbol is assigned a value that is never used: "Store7"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2860) : warning 204: symbol is assigned a value that is never used: "Store8"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2861) : warning 204: symbol is assigned a value that is never used: "Store9"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862) : warning 204: symbol is assigned a value that is never used: "Store9Exit"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw0"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw1"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw10"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw11"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw12"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw13"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw14"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw16"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw17"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw18"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw19"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw2"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw20"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw21"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw23"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw25"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw27"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw28"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw29"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw3"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw30"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw31"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw32"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw33"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw34"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw35"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw36"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw37"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw38"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw39"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw4"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw40"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw41"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw5"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw6"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw7"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw8"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "Textdraw9"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "TickCount"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "TimeProgress"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "TotalCP"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "TotalRaces"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "WeaponDualRoom1"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "WeaponDualRoom2"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "WeaponDualRoom3"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "WeaponDualRoom4"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "WhatCar"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "blub"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "cVeh"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "chosenpid"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "cnrjail"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "cnrjailtiming"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(2862 -- 209) : warning 203: symbol is never used: "commanddelay"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(28) : warning 204: symbol is assigned a value that is never used: "destroyTimer"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(28 -- 209) : warning 203: symbol is never used: "eventTimer"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(28 -- 209) : warning 203: symbol is never used: "gArmour"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(28 -- 209) : warning 203: symbol is never used: "gHealth"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(28 -- 209) : warning 203: symbol is never used: "gLoginAttempts"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(28 -- 209) : warning 203: symbol is never used: "gTime"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(231) : warning 204: symbol is assigned a value that is never used: "gate1"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(232) : warning 204: symbol is assigned a value that is never used: "gate2"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(233) : warning 204: symbol is assigned a value that is never used: "gate3"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(233 -- 209) : warning 203: symbol is never used: "glassObject"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(161) : warning 204: symbol is assigned a value that is never used: "groupID"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(238) : warning 204: symbol is assigned a value that is never used: "heavy"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(238 -- 209) : warning 203: symbol is never used: "hshot"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(238 -- 209) : warning 203: symbol is never used: "iCanUse"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(238 -- 209) : warning 203: symbol is never used: "jailtimer"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(238 -- 209) : warning 203: symbol is never used: "jailtimer2"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(21) : warning 204: symbol is assigned a value that is never used: "job1"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(24) : warning 204: symbol is assigned a value that is never used: "job2"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(234) : warning 204: symbol is assigned a value that is never used: "lift"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27) : warning 204: symbol is assigned a value that is never used: "matspoint1"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "nextglass"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "playerVehicle"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "rCounter"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "robberytime"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(27 -- 209) : warning 203: symbol is never used: "robberytiming"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(236) : warning 204: symbol is assigned a value that is never used: "runnies"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(1484) : warning 204: symbol is assigned a value that is never used: "spawntime"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(1485) : warning 204: symbol is assigned a value that is never used: "spawntiming"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(1485 -- 209) : warning 203: symbol is never used: "timer"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(29) : warning 204: symbol is assigned a value that is never used: "timez"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(237) : warning 204: symbol is assigned a value that is never used: "walkies"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(237 -- 209) : warning 203: symbol is never used: "x1"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(237 -- 209) : warning 203: symbol is never used: "xCharacters"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(35) : warning 204: symbol is assigned a value that is never used: "xReactionTimer"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(35 -- 209) : warning 203: symbol is never used: "y1"
> C:\Users\Yassine\Documents\GitHub\Saplayground\sap.pwn(35 -- 209) : warning 203: symbol is never used: "z1"
> 6 Errors.

damn idk ^^^??

what about you @Sreyas-Sreelal  ?? 

@AndySedeyn  if u wanna help me come :)

**Comment by AndySedeyn** [comment]
Is `irc.inc` successfully being included?

**Comment by Sreyas-Sreelal** [comment]
Most probably some of the  module inclusion occurred before including include.As Andy said you should check the inclusion

**Comment by LVPYassine** [comment]
https://github.com/saplayground/San-Andreas-Playground/blob/master/SAPData/Freeroam/Server/Includes.pwn#L23

it's compelety included :/

**Comment by LVPYassine** [comment]
Fixed !
