### ISSUE TITLE
Should update the YSI to newer version

### ISSUE THREAD

**Issue by Sreyas-Sreelal** [saplayground/San-Andreas-Playground#6]
YSI version now being used have some deprecated functions like in y_iterate it should be updated and replace all foreach code with newest version.Also there are some for loops to be replaced with foreach.

**Comment by LVPYassine** [comment]
There a newer version ? ._. 
Notice : i edited YSI on This Gamemode for some reason (Optimized and comp... With SAP)

anyway send me link of The newer version and let's start :D

**Comment by LVPYassine** [comment]
Now we need to update Admin.pwn to the lastest version of foreach

**Comment by Sreyas-Sreelal** [comment]
https://github.com/Misiur/YSI-Includes
