### ISSUE TITLE
Duel Issues

### ISSUE THREAD

**Issue by LVPYassine** [saplayground/San-Andreas-Playground#7]
> [D:\pawno-master\include\SAPData/Gameplay/Duel.pwn(703) : error 008: must be a constant expression; assumed zero ](url)

We need to fix this ^errors 

SS Do you have any idea ?

fix it man :D @Sreyas-Sreelal !!

**Comment by LVPYassine** [comment]
why closing this ? :/

**Comment by Sreyas-Sreelal** [comment]
i misread what you said i read it its fixed man

**Comment by LVPYassine** [comment]
i say fix it man <--- it's still need a fix :/ 

@Sreyas-Sreelal

**Comment by Sreyas-Sreelal** [comment]
i will do it as i get home

**Comment by LVPYassine** [comment]
Nice Thanks :-1:

**Comment by Sreyas-Sreelal** [comment]
Hmm the thing was a compiler needs curly brackets even if there is only one statement in case part i think that caused it try it now its compiling fine for new compilers.

**Comment by LVPYassine** [comment]
Nice then let's close this :D

**Comment by LVPYassine** [comment]
not yet

**Comment by LVPYassine** [comment]
Closed By a Temp-Fix
