### ISSUE TITLE
Fixing The last errors before the next release

### ISSUE THREAD

**Issue by LVPYassine** [saplayground/San-Andreas-Playground#8]
- [x] Forwarding For CnR System

- [x] Updating YSI Version to lastest 

- [x] Fixing FormatMSG Errors :/ 

- [x] Fixing Duel System Errors :/

- [x] Last steps for The New CnR System 

- [x] Race Fast Fix

- [x] Build Race Removing

 

Credits to Aleem -|Half of CnR script|-

Let's start ! 

Errors : http://pastebin.com/DUJ2LDVq

**Comment by Sreyas-Sreelal** [comment]
FormatMSG is not defined?

**Comment by LVPYassine** [comment]
is Defined

**Comment by LVPYassine** [comment]
ALL fixed now we need to fix the duel issue
